version: '3'
services:
  web:
    image: nginx
  # db:
  #   image: mysql
  #   ports:
  #   - "3306:3306"
  #   environment:
  #   - MYSQL_ROOT_PASSWORD=root
  #   - MYSQL_USER=userclear
  #   - MYSQL_PASSWORD=root
  #   - MYSQL_DATABASE=demodb

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'myDb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      - wpsite
    # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
networks: 
  wpsite:
    driver: bridge