#  MySql and mariadb docker compose file
version: '3.1'
services:

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mydb
  #   ports: 
  #    - "3308:3306"

  mariadb:
     image: mariadb
     restart: always
     environment:
      MYSQL_DATABASE: 'myDb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
     ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
     expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
     volumes:
      - my-db:/var/lib/mysql

volumes:
    my-db:
