version: '3'
services: 
# Install Nginx web server 
 web:
  image: nginx
  container_name: nginxServer
  ports: 
  - '9090:80'
  # Intsall mysql latest version 
 db:
    image: mysql
    container_name: mySql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports: 
     - '3306:3306'
    expose: 
     - '3306'
# Install adminer (Adminer is a tool for managing in MySQL.)
 adminer:
   image: adminer
   container_name: db_adminer
   restart: always
  #  http://localhost:8090/adminer
   ports: 
    - '8090:8080'